{"cell_type":{"ae0cacbe":"code","d832babe":"code","73cba9b4":"code","fd2228be":"code","7f0ce82d":"code","c37df624":"code","9c14f95e":"code","3cdab080":"code","5b02bbf2":"code","8debb3ca":"code","c082ab6c":"markdown","115af383":"markdown"},"source":{"ae0cacbe":"import numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\ndata = pd.read_csv(\"..\/input\/covid-world-vaccination-progress\/country_vaccinations.csv\")\ndata.head()","d832babe":"data.info()","73cba9b4":"data.describe()","fd2228be":"data['date']\npd.to_datetime(data.date)","7f0ce82d":"pd.to_datetime(data.date)\ndata.country.value_counts()","c37df624":"data = data[data.country.apply(lambda x: x not in [\"England\", \"Scotland\", \"Wales\", \"Northern Ireland\"])]\ndata.country.value_counts()\n","9c14f95e":"data.vaccines.value_counts()","3cdab080":"df = data[[\"vaccines\", \"country\"]]\ndf.head()","5b02bbf2":"dict_ = {}\nfor i in df.vaccines.unique():\n  dict_[i] = [df[\"country\"][j] for j in df[df[\"vaccines\"]==i].index]\n\nvaccines = {}\nfor key, value in dict_.items():\n  vaccines[key] = set(value)\nfor i, j in vaccines.items():\n  print(f\"{i}:>>{j}\")","8debb3ca":"import plotly.express as px\nimport plotly.offline as py\n\nvaccine_map = px.choropleth(data, locations = 'iso_code', color = 'vaccines')\nvaccine_map.update_layout(height=300, margin={\"r\":0,\"t\":0,\"l\":0,\"b\":0})\nvaccine_map.show()","c082ab6c":"So we have almost all the Covid-19 vaccines available in this dataset. Now I will create a new DataFrame by only selecting the vaccine and the country columns to explore which vaccine is taken by which country:","115af383":"The United Kingdom is made up of England, Scotland, Wales, and Northern Ireland. But in the above data, these countries are mentioned separately with the same values as in the United Kingdom. So this may be an error while recording this data. So let\u2019s see how we can fix this error:"}}