{"cell_type":{"3c768610":"code","c8fbb750":"code","484608fb":"code","30c91677":"code","d29c05b7":"code","f80dc447":"code","ab3615fd":"code","f079803c":"code","1c5bef29":"code","edc14a8b":"code","db79df73":"code","75d22676":"code","f46b1ba9":"code","a64f1368":"code","29388379":"code","82073f87":"code","08ed2180":"code","1f90e344":"code","1ac43b8f":"code","7d4adf32":"code","f2729e8a":"code","e617061d":"code","5266b798":"code","5e8aa1f3":"code","f1285c13":"markdown","94887ed3":"markdown","43bf2a38":"markdown","6b5b427d":"markdown","9d87aa4e":"markdown","569a56a9":"markdown","7344e26d":"markdown","bb957876":"markdown","f514e307":"markdown","d43626b4":"markdown","04419585":"markdown","6d25047e":"markdown"},"source":{"3c768610":"import pandas as pd\nimport numpy as np\nimport seaborn as sns\nimport matplotlib.pyplot as plt\nfrom plotly.offline import init_notebook_mode\ninit_notebook_mode()","c8fbb750":"train = pd.read_csv('..\/input\/metadata_train.csv')","484608fb":"train.head(10)","30c91677":"train.shape","d29c05b7":"train.columns","f80dc447":"print(train.signal_id.dtype)\nprint(train.id_measurement.dtype)\nprint(train.phase.dtype)\nprint(train.target.dtype)","ab3615fd":"train.phase.value_counts()","f079803c":"train.isna().any()","1c5bef29":"train.target.value_counts()","edc14a8b":"train['target'].value_counts().plot.bar()","db79df73":"train.groupby([\"id_measurement\"]).sum().query(\"target > 0\").shape[0]","75d22676":"train['id_measurement'].unique().shape[0]","f46b1ba9":"print('{} out of {} ids contain a fault in at least one of three phases. This is {:.0f}%'.format(\n      train.groupby([\"id_measurement\"]).sum().query(\"target > 0\").shape[0],\n      train['id_measurement'].unique().shape[0],\n      (train.groupby([\"id_measurement\"]).sum().query(\"target > 0\").shape[0]*100)\/train['id_measurement'].unique().shape[0]))","a64f1368":"train.groupby([\"id_measurement\"]).sum()['target'].value_counts().plot.bar()","29388379":"train.groupby([\"id_measurement\"]).sum()['target'].value_counts()","82073f87":"test = pd.read_csv('..\/input\/metadata_test.csv')","08ed2180":"test.head()","1f90e344":"test.shape","1ac43b8f":"test.phase.value_counts()","7d4adf32":"train_sig = pd.read_parquet('..\/input\/train.parquet')","f2729e8a":"train_sig.head()","e617061d":"train_sig.shape","5266b798":"fig, ax = plt.subplots(figsize=(12,10))\nfor i in range(3):\n    sns.lineplot(train_sig.index, train_sig[str(i)])","5e8aa1f3":"fig, ax = plt.subplots(figsize=(12,10))\nfor i in range(3,6):\n    sns.lineplot(train_sig.index, train_sig[str(i)])","f1285c13":"Check for missing values","94887ed3":"From [this](https:\/\/www.kaggle.com\/c\/vsb-power-line-fault-detection\/discussion\/75771) discussion and other [EDA kernels posted](https:\/\/www.kaggle.com\/go1dfish\/basic-eda), it looks like this isn't an isolated case. It would be worth looking at these signals again after wavelet transformations and denoising as per Tomas' problem description thread.","43bf2a38":"Presumably the fault lies at the beginning of the signals in the second plot but there is not a huge amount of difference between the two graphs. Looks like a significant amount of interference in the power lines in the first plot have led to noisy signals, much like:\n\n![samples](https:\/\/storage.googleapis.com\/kaggle-forum-message-attachments\/445388\/10942\/samples.png)","6b5b427d":"Signals with no fault","9d87aa4e":"Looks like if a fault exists, all three lines usually have a fault simultaneously","569a56a9":"# Train signal data","7344e26d":"Check how many ids have at least 1 fault","bb957876":"## Test metadata","f514e307":"Signals with faults","d43626b4":"How many ids in total?","04419585":"Check distribution of target","6d25047e":"## Train metadata"}}