{"cell_type":{"b4aa8943":"code","0c62bb2d":"code","30182974":"code","d2ab9542":"code","143b44c7":"markdown","bff74139":"markdown","c963ef33":"markdown"},"source":{"b4aa8943":"import pandas as pd","0c62bb2d":"sample = pd.read_csv('\/kaggle\/input\/tensorflow2-question-answering\/sample_submission.csv').set_index('example_id')\nsample.sort_index().head()","30182974":"test = pd.read_json('\/kaggle\/input\/tensorflow2-question-answering\/simplified-nq-test.jsonl', orient = 'records', lines = True).set_index('example_id')\ntest.index = test.index.astype(str)\ntest.sort_index().head()","d2ab9542":"test2 = pd.read_json('\/kaggle\/input\/tensorflow2-question-answering\/simplified-nq-test.jsonl',\n                    dtype = {'example_id': 'Object'},\n                    lines = True).set_index('example_id')\ntest2.sort_index().head()","143b44c7":"## Solution\nSpecify dtype as 'Object' for `example_id`","bff74139":"## Problem - Original Post\nIt seems that this dataset has different examples in the `sample_submission.csv` as compared to the test set `simplified-nq-test.jsonl`. This very short kernel illustrates that difference.","c963ef33":"## Update\nThanks to comments by @mourad below and @kashnitsky in [this thread](https:\/\/www.kaggle.com\/c\/tensorflow2-question-answering\/discussion\/123781https:\/\/www.kaggle.com\/c\/tensorflow2-question-answering\/discussion\/123781), I have realised this is not a data conflict but an error in my code. My code uses `pandas.read_json` without specifying data type, so the `example_id` is read as an integer type with insufficient accuracy for the 20-digit id.\n\nI have added a solution (specifying 'Object' data type) in the last cell of this notebook, in case anyone else gets stuck on a similar problem."}}