{"cell_type":{"914ba20f":"code","580985c9":"code","c3a00eb0":"code","015697ab":"code","e1518bff":"markdown"},"source":{"914ba20f":"from IPython.display import clear_output\n!pip3 install rx\nclear_output()","580985c9":"import rx \nfrom rx import of,operators as op","c3a00eb0":"DATA1 = of(5,3,-1,8,-2,10)\nDATA2 = of(100,200,300,400,500)\nERROR_MESSAGE =\"Error occurred\"","015697ab":"def checkError(e):\n    if (e <= 0):\n        raise Exception(ERROR_MESSAGE)\n    else:\n        return e\n    \n\nDATA1.pipe(\n   op.map(lambda e : checkError(e)),\n   op.catch(DATA2) # change data \n).subscribe(\n    on_next = lambda x: print(\"result= {0}\".format(x)),\n    on_error = lambda e: print(\"error= {0}\".format(e))\n)","e1518bff":"# catch\n\nwill terminate the source observable \n\nwhen there is an exception."}}